name: Ruby Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        backend: ['ruby', 'ruby-agraph'] # ruby runs tests with 4store backend and ruby-agraph runs with AllegroGraph backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up solr configsets
      run: ./test/solr/generate_ncbo_configsets.sh
    - name: create config.rb file
      run: cp config/config.test.rb config/config.rb
    - name: Build docker-compose
      run: docker-compose build
    - name: Run unit tests
      # unit tests are run inside a container
      run: docker-compose run ${{ matrix.backend }} wait-for-it solr-ut:8983 -- bundle exec rake test TESTOPTS='-v'
