name: Ruby Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up solr configsets
      working-directory: ./test
      run: solr/generate_ncbo_configsets.sh
    - name: create config.rb file
      run: cp config/config.rb.sample config/config.rb
    - name: Build docker-compose
      working-directory: ./test
      run: docker-compose build
    - name: Run unit tests
      working-directory: ./test
      run: docker-compose run ld-unit-test wait-for-it ld-solr-ut:8983 -- bundle exec rake test TESTOPTS='-v'

